language: ruby
sudo: false
rvm:
  - 2.3.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site

notifications:
  email: false
