title:             CARLA
email:             carla.simulator@gmail.com
description:
author:            Carla Team
baseurl:           ""
url:               http://carla.org/ # http://carla-simulator.github.io/

# Social Profiles
cvc_page:          http://www.cvc.uab.es/
intel_page:        https://www.intel.com/
github_username:   carla-simulator
youtube_channel:   UC1llP9ekCwt8nEJzMJBQekg

# Build settings
markdown:          kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink:         pretty

paginate:          100
paginate_path:     "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
